# Generated by Django 6.0 on 2026-01-09 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisPred',
            fields=[
                ('id_analisis', models.AutoField(primary_key=True, serialize=False)),
                ('id_paciente_fk', models.IntegerField()),
                ('id_caso_fk', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuestraSaliva',
            fields=[
                ('id_muestra', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_imagen', models.TextField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras_saliva', to='api.analisispred')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAnalisis',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('nucleos', models.IntegerField()),
                ('micronucleos', models.IntegerField()),
                ('membranas', models.IntegerField()),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='api.muestrasaliva')),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisMascara',
            fields=[
                ('id_mascara_analisis', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mascara', models.CharField(max_length=50)),
                ('ruta_mascara', models.TextField()),
                ('algoritmo', models.CharField(max_length=100)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascaras', to='api.resultadoanalisis')),
            ],
        ),
    ]
