# Generated by Django 6.0 on 2026-02-19 00:31

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id_analisis', models.AutoField(primary_key=True, serialize=False)),
                ('version_modelo', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En Proceso'), ('listo', 'Listo'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analisis',
            },
        ),
        migrations.CreateModel(
            name='CasoClinico',
            fields=[
                ('id_caso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('diagnostico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'caso_clinico',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='AnalisisResultados',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('total_membranas', models.IntegerField(default=0)),
                ('total_nucleos', models.IntegerField(default=0)),
                ('total_micronucleos', models.IntegerField(default=0)),
                ('total_binucleadas', models.IntegerField(default=0)),
                ('total_trinucleadas', models.IntegerField(default=0)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('version_calculo', models.PositiveIntegerField(default=1)),
                ('id_analisis_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='api.analisis')),
            ],
            options={
                'db_table': 'analisis_resultados',
            },
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id_muestra', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_muestra', models.CharField(choices=[('sangre', 'Sangre'), ('saliva', 'Saliva')], default='saliva', max_length=20)),
                ('ruta_imagen', models.ImageField(upload_to=api.models.path_muestras)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('fecha_toma', models.DateTimeField(auto_now_add=True)),
                ('id_caso_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='api.casoclinico')),
            ],
            options={
                'db_table': 'muestras',
            },
        ),
        migrations.AddField(
            model_name='analisis',
            name='id_muestra_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='api.muestra'),
        ),
        migrations.AddField(
            model_name='casoclinico',
            name='id_paciente_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='api.paciente'),
        ),
        migrations.CreateModel(
            name='AnalisisArchivos',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('contenido_json', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('es_resultado_modelo', models.BooleanField(default=True, help_text='True = salida automática, False = edición humana')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_analisis_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='api.analisis')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analisis_archivos',
                'ordering': ['-version'],
                'unique_together': {('id_analisis_fk', 'version')},
            },
        ),
    ]
