# Generated by Django 6.0 on 2026-01-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisismascara',
            name='ruta_mascara',
        ),
        migrations.RemoveField(
            model_name='muestrasaliva',
            name='ruta_imagen',
        ),
        migrations.AddField(
            model_name='analisismascara',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mascaras/saliva/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='muestrasaliva',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='muestras/saliva/%Y/%m/'),
        ),
    ]
