# Generated by Django 6.0 on 2026-02-24 19:53

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisJob',
            fields=[
                ('id_job', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('total_imagenes', models.IntegerField(default=0)),
                ('procesadas', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
                ('es_reproceso', models.BooleanField(default=False)),
                ('version_modelo', models.CharField(default='cellpose-v1', max_length=50)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analisis_job',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='analisisarchivos',
            index=django.contrib.postgres.indexes.GinIndex(fields=['contenido_json'], name='gin_contenido_json'),
        ),
        migrations.AddIndex(
            model_name='analisisarchivos',
            index=models.Index(fields=['id_analisis_fk'], name='idx_archivo_analisis'),
        ),
        migrations.AddIndex(
            model_name='analisisarchivos',
            index=models.Index(condition=models.Q(('activo', True)), fields=['id_analisis_fk'], name='idx_archivo_activo'),
        ),
        migrations.AddField(
            model_name='analisisjob',
            name='id_caso_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.casoclinico'),
        ),
    ]
