# Generated by Django 6.0 on 2026-02-03 01:06

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id_analisis', models.AutoField(primary_key=True, serialize=False)),
                ('version_modelo', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En Proceso'), ('listo', 'Listo'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analisis',
            },
        ),
        migrations.RemoveField(
            model_name='analisispred',
            name='id_caso_fk',
        ),
        migrations.RemoveField(
            model_name='analisispred',
            name='id_paciente_fk',
        ),
        migrations.RemoveField(
            model_name='muestrasaliva',
            name='analisis',
        ),
        migrations.RemoveField(
            model_name='caso',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='resultadoanalisis',
            name='muestra',
        ),
        migrations.AlterModelTable(
            name='paciente',
            table='paciente',
        ),
        migrations.CreateModel(
            name='AnalisisArchivos',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('mascara', 'Mascara'), ('json_raw', 'JSONB_Result'), ('preview', 'Preview')], max_length=20)),
                ('ruta_archivo', models.FileField(upload_to=api.models.path_mascaras)),
                ('id_analisis_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='api.analisis')),
            ],
            options={
                'db_table': 'analisis_archivos',
            },
        ),
        migrations.CreateModel(
            name='AnalisisEdicion',
            fields=[
                ('id_edicion', models.AutoField(primary_key=True, serialize=False)),
                ('edicion_jsonb', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_analisis_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ediciones', to='api.analisis')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analisis_edicion',
            },
        ),
        migrations.CreateModel(
            name='AnalisisResultados',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('resultado_jsonb', models.JSONField()),
                ('metadatos_jsonb', models.JSONField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('id_analisis_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='api.analisis')),
            ],
            options={
                'db_table': 'analisis_resultados',
            },
        ),
        migrations.CreateModel(
            name='CasoClinico',
            fields=[
                ('id_caso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('id_paciente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='api.paciente')),
            ],
            options={
                'db_table': 'caso_clinico',
            },
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id_muestra', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_muestra', models.CharField(choices=[('sangre', 'Sangre'), ('saliva', 'Saliva')], default='saliva', max_length=20)),
                ('ruta_imagen', models.ImageField(upload_to=api.models.path_muestras)),
                ('fecha_toma', models.DateTimeField(auto_now_add=True)),
                ('id_caso_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='api.casoclinico')),
            ],
            options={
                'db_table': 'muestras',
            },
        ),
        migrations.AddField(
            model_name='analisis',
            name='id_muestra_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='api.muestra'),
        ),
        migrations.DeleteModel(
            name='AnalisisMascara',
        ),
        migrations.DeleteModel(
            name='AnalisisPred',
        ),
        migrations.DeleteModel(
            name='Caso',
        ),
        migrations.DeleteModel(
            name='MuestraSaliva',
        ),
        migrations.DeleteModel(
            name='ResultadoAnalisis',
        ),
    ]
