# Generated by Django 6.0 on 2026-01-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_analisismascara_ruta_mascara_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisismascara',
            name='imagen',
            field=models.ImageField(upload_to='mascaras/saliva/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='muestrasaliva',
            name='imagen',
            field=models.ImageField(upload_to='muestras/saliva/%Y/%m/'),
        ),
    ]
