# Generated by Django 6.0 on 2026-02-03 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_analisis_remove_analisispred_id_caso_fk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisisedicion',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='analisisarchivos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analisisarchivos',
            name='tipo',
            field=models.CharField(choices=[('mascara_nucleo', 'Máscara Núcleo'), ('mascara_micronucleo', 'Máscara Micronúcleo'), ('mascara_membrana', 'Máscara Membrana'), ('preview', 'Preview PNG'), ('json_raw', 'JSON Raw')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='analisisarchivos',
            unique_together={('id_analisis_fk', 'tipo')},
        ),
    ]
