# Generated by Django 6.0.1 on 2026-02-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_analisisedicion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
